services:
  - type: web
    name: django-portfolio
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd portfolio && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd portfolio && gunicorn portfolio.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
