services:
  - type: web
    name: django-portfolio
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd /opt/render/project/src && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src python -m gunicorn --bind 0.0.0.0:$PORT portfolio.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
