# Generated by Django 5.2.6 on 2025-09-26 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resume')),
                ('pdf_file', models.FileField(help_text='Upload your resume in PDF format', upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text='Set as active resume to display on portfolio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
